fix(install-packages): linux errors

diff --git a/run_onchange_install-packages.sh.tmpl b/run_onchange_install-packages.sh.tmpl
--- a/run_onchange_install-packages.sh.tmpl
+++ b/run_onchange_install-packages.sh.tmpl
@@ -1,33 +1,38 @@
 {{ if eq .chezmoi.os "darwin" -}}
 #!/bin/bash
-echo "Installing macOS Homebrew packages and casks..."
-
-# --- Check if Homebrew is installed ---
+echo "Installing macOS Homebrew packages and casks ..."
 if ! command -v brew &>/dev/null; then
-  echo "Homebrew not found. Install Homebrew first."
+  echo "Error: Homebrew not found on macOS. Install Homebrew first." >&2
   exit 1
 fi
 
 brew bundle --file=/dev/stdin <<EOF
-{{ range .packages.darwin.brews -}}
+{{- range .packages.darwin.brews }}
 brew {{ . | quote }}
 {{ end -}}
 {{ range .packages.darwin.casks -}}
 cask {{ . | quote }}
 {{ end -}}
 EOF
+echo "Homebrew bundle for macOS complete."
+
 {{ else if eq .chezmoi.os "linux" -}}
 #!/bin/bash
 echo "Installing Linux packages..."
-# --- Install Homebrew packages (if Homebrew is installed on Linux) ---
-if command -v brew &>/dev/null; then
-  echo "Installing Homebrew packages..."
-  brew bundle --file=/dev/stdin <<EOF
-    {{ range .packages.linux.brews -}}
-    brew {{ . | quote }}
-    {{ end -}}
-EOF
-else
-  echo "Homebrew not found on Linux. Skipping Homebrew package installation."
+
+# --- Install Homebrew packages ---
+if ! command -v brew &>/dev/null; then
+  echo "Error: Homebrew not found on Linux. Install Homebrew first." >&2
+  exit 1
 fi
+{{ if .packages.linux.brews -}}
+echo "Passing linux brews:"
+brew bundle --file=/dev/stdin <<EOF
+{{- range .packages.linux.brews }}
+brew {{ . | quote }}
+{{-   end }}
+EOF
+echo "Homebrew bundle for Linux complete."
+{{ else -}}
+echo "No Homebrew packages or casks defined for Linux brew. Skipping."
 {{ end -}}
